In [2]:

import pandas as pd
import os

In [7]:
os.chdir("D:\Trabalho\Microdados\DADOS")

NameError: name 'pwd' is not defined

In [8]:
pwd

'D:\\Trabalho\\Microdados\\DADOS'

#### Para saber quual nome dos sheets

In [ ]:

# Substitua 'seu_arquivo.xlsx' pelo nome do seu arquivo Excel
nome_do_arquivo = 'MICRODADOS_ENEM_2022.xlsx'

# Carregar as informações do arquivo Excel
excel_info = pd.ExcelFile(nome_do_arquivo)

# Obter nomes das planilhas disponíveis
nomes_das_planilhas = excel_info.sheet_names

# Imprimir os nomes das planilhas
print("Planilhas disponíveis:", nomes_das_planilhas)

#### Importar arquivo .csv

In [19]:

df=pd.read_csv('MICRODADOS_ENEM_2022.csv', sep=';', encoding='latin-1')

In [20]:
pd.set_option('display.max_columns', None)  # Configura para exibir todas as colunas
df.head(5)

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210057943671,2022,14,M,2,2,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5300108,Brasília,53,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,A,A,B,3,B,B,B,B,B,B,B,A,B,B,B,A,A,A,A,A,A,A,A,A
1,210057516120,2022,14,M,2,1,1,1,16,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5300108,Brasília,53,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D,E,E,3,Q,D,E,E,E,E,E,E,E,E,E,E,B,E,B,B,E,B,E,B
2,210057280536,2022,5,F,1,2,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2925758,Presidente Tancredo Neves,29,BA,1,1,1,1,1087.0,1056.0,1066.0,1078.0,421.1,546.0,498.8,565.3,DCDCEBADDABEDBCBEAEACCDDECEEBECBECAAECDDDDBCE,DBDABCADADECACBDCCEDACCCECDDABDCEADABCBCBAEAB,ABEABADCCADCAAAACDADDCECBAAACADABDEBCBCAAACEB,BDEBACECBCAEBABEDBABDACBCABCDEDEADBAABCBEACCD,1,DDECDBEACCAEBEAEBBCCDDCBDDACBEACEABCEABEDADBA,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,DECDBDCEAADDBCABEDCAAADCCECEEBABEEAAABDBCCCABE...,BEEDAEABDDCEBDBAAAAACXCBCCCBCCDBDEECBDCABEECD,1.0,140.0,200.0,120.0,140.0,160.0,760.0,E,F,A,D,2,B,A,B,C,A,A,B,B,A,A,A,A,A,A,A,A,C,A,A,B
3,210055724397,2022,6,M,1,3,1,1,2,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3201308,Cariacica,32,ES,1,1,1,1,1088.0,1058.0,1067.0,1077.0,490.7,388.6,357.8,416.0,BACBBABBCAABCABBCBACBCBCBACABACABCBDBCBABAACA,BBCAACACDCABCBACCABABCBACBCABBBBBABCBACCBCBBA,ABACCCCBCBAADABBBACABBAABACCBCBBCDCACABABCAAC,BBBACCBABABBBBACDABBBBABCCBBCABBBBAACABBACBCB,1,DDCBBCCDDAADBAABEDABCEEAEBAEBECBDDEBEACCEACCD,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECBABEACD,CDBEDACDEACAABDBDBDDCABEEECEABECABEEAAACBBEBAD...,CCCCBXCBABECBEABDDDBDECDBDCAACEECCEBDBAAAEDAE,1.0,120.0,40.0,40.0,100.0,20.0,320.0,C,A,A,B,3,A,A,C,D,A,A,B,A,B,A,B,A,A,C,A,A,C,B,B,B
4,210055097896,2022,4,M,0,3,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1506203,Salinópolis,15,PA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,B,A,B,2,B,A,B,B,A,A,B,A,A,A,A,A,A,A,A,A,B,A,A,A

In [ ]:
pd.set_option('display.max_columns', 10)

In [21]:
df1 = df.copy

In [22]:
df1 = df.head(1000)

In [23]:
df1.tail()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
995,210055642015,2022,6,M,1,3,1,1,4,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2801009,Campo do Brito,28,SE,1,1,1,1,1087.0,1056.0,1066.0,1078.0,400.0,537.4,500.0,493.9,BCDACCBDCCBCBBCACBEDCCABDAEABABBE*CBECADBEBCD,EDAABADDADCBEBADCEDDAAACECBCAC*CDDAABEADDCAEE,EAEADDCBCABEDEDAADECEBDEEDBACEBADCBCBDCCDBBEB,BDDBACCBCBCDCABCCDBEBBCACDBEECDBCEBBADBEDABBE,1,DDECDBEACCAEBEAEBBCCDDCBDDACBEACEABCEABEDADBA,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,DECDBDCEAADDBCABEDCAAADCCECEEBABEEAAABDBCCCABE...,BEEDAEABDDCEBDBAAAAACXCBCCCBCCDBDEECBDCABEECD,1.0,100.0,160.0,140.0,120.0,180.0,700.0,B,B,A,A,2,B,A,B,C,A,A,B,A,A,A,A,A,A,B,A,A,C,A,B,B
996,210055591467,2022,3,M,1,2,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2704302,Maceió,27,AL,1,1,1,1,1088.0,1058.0,1067.0,1077.0,443.9,544.9,529.7,484.4,DADCCAEEEEDEBBEBBCACBACBCEBABCEBCDECADCCDBDAC,DBDEAADBDCBBBEDDDEACBBDEBCBAAEEACBEEEBEEBCCCA,ACDEEDABDDEEBDCDADAEACBACAEDBBEDEABBDBDEDCCCB,DDABC*CADEBBBDDEDABBCBDEDAEEEDDCDBBEBDCEEEAAC,1,DDCBBCCDDAADBAABEDABCEEAEBAEBECBDDEBEACCEACCD,CEDAAADBAECBCDDADEABCBECAEEDAEBABBCDECBABEACD,CDBEDACDEACAABDBDBDDCABEEECEABECABEEAAACBBEBAD...,CCCCBXCBABECBEABDDDBDECDBDCAACEECCEBDBAAAEDAE,1.0,140.0,140.0,120.0,120.0,120.0,640.0,C,D,D,D,3,C,A,C,D,B,A,B,B,B,A,A,A,A,D,B,A,D,A,B,B
997,210057387803,2022,2,M,1,1,1,2,0,2,1.0,0,2603454.0,Camaragibe,26.0,PE,2.0,1.0,1.0,2603454,Camaragibe,26,PE,1,1,1,1,1087.0,1056.0,1066.0,1078.0,561.4,573.7,579.1,600.4,DEDADBEBECBABBCBCACCDDDCADEECCAEBAACDBEBDACCD,ECBABEDDDBBBBDEBCEEDABACDEADACBDDDCACDECDCACE,DDCDBDDBCADAAEAAADBCEADDBBBAADAEBDCCDEABEECBA,BEEBABAADBBDBACCEEECBDCADBDBCBDDBCDDEBADCBBBC,0,DDECDBEACCAEBEAEBBCCDDCBDDACBEACEABCEABEDADBA,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,DECDBDCEAADDBCABEDCAAADCCECEEBABEEAAABDBCCCABE...,BEEDAEABDDCEBDBAAAAACXCBCCCBCCDBDEECBDCABEECD,1.0,140.0,120.0,120.0,120.0,100.0,600.0,H,G,B,E,3,C,A,B,C,A,B,B,B,B,B,B,A,A,B,A,A,D,A,B,B
998,210057257170,2022,8,F,1,2,1,1,5,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2930501,Serrinha,29,BA,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,B,C,A,A,6,A,A,B,D,A,B,B,A,A,A,A,A,A,B,A,A,C,A,A,B
999,210054718093,2022,3,M,1,1,1,1,1,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4322400,Uruguaiana,43,RS,1,1,1,1,1087.0,1056.0,1066.0,1078.0,581.1,613.5,617.7,603.0,CDACDCBAEBAABADBBBCCBECCCEEBDEBDDDCBCEBBAADDB,EABACBDDAAEABBEBEEEBAECCDEEDABEDDCEABDEDACACD,DECDBCDBCCAAEDAAEDCCAAEEBBBAAAAABDBCCCBBCECBD,BEEDACACDACDDCADAEBCADEBBCBADCBECCBBABCADBBCA,0,DDECDBEACCAEBEAEBBCCDDCBDDACBEACEABCEABEDADBA,ECBABCDDAAECBCBECAEBAEACDEEDABBCDDEABCEDAAADB,DECDBDCEAADDBCABEDCAAADCCECEEBABEEAAABDBCCCABE...,BEEDAEABDDCEBDBAAAAACXCBCCCBCCDBDEECBDCABEECD,1.0,140.0,200.0,140.0,160.0,160.0,800.0,E,C,B,C,7,C,A,B,C,C,B,B,B,B,A,B,A,A,B,A,A,C,A,A,B

In [ ]:
os.chdir("D:\Trabalho\Microdados\DADOS")

In [24]:
df1.to_excel('D:\Repositório GIT\Projetos\IBGE\Datasets\Educação\Microdado_Teste.xlsx', index=False)